// Commodity variant: Major mining companies and their key locations
// Covers headquarters, regional offices, and major mine sites for top operators

export interface CommodityMiner {
  id: string;
  name: string;
  lat: number;
  lon: number;
  country: string;
  city: string;
  siteType: 'headquarters' | 'mine' | 'processing' | 'regional-office';
  sector: 'Gold' | 'Silver' | 'Copper' | 'Lithium' | 'Cobalt' | 'Rare Earths' | 'Nickel' | 'PGMs' | 'Iron Ore' | 'Uranium' | 'Diversified' | 'Coal' | 'Aluminum' | 'Zinc';
  operator: string;
  mineralTypes: string[];
  status: 'operating' | 'development' | 'care-and-maintenance' | 'exploration';
  stockSymbol?: string;
  productionCapacity?: string;
  description?: string;
  employees?: number;
  marketCapUSD?: number; // in billions
}

export const COMMODITY_MINERS: CommodityMiner[] = [
  // ============================================================
  // DIVERSIFIED MEGA-MINERS (Headquarters)
  // ============================================================
  {
    id: 'bhp-hq',
    name: 'BHP',
    lat: -37.8136,
    lon: 144.9631,
    country: 'Australia',
    city: 'Melbourne',
    siteType: 'headquarters',
    sector: 'Diversified',
    operator: 'BHP',
    mineralTypes: ['Iron Ore', 'Copper', 'Nickel', 'Coal', 'Potash'],
    status: 'operating',
    stockSymbol: 'BHP',
    description: 'World\'s largest mining company by market cap. Major iron ore, copper, and coal producer.',
    employees: 80000,
    marketCapUSD: 130,
  },
  {
    id: 'bhp-london',
    name: 'BHP London',
    lat: 51.5074,
    lon: -0.1278,
    country: 'United Kingdom',
    city: 'London',
    siteType: 'regional-office',
    sector: 'Diversified',
    operator: 'BHP',
    mineralTypes: ['Iron Ore', 'Copper', 'Nickel', 'Coal'],
    status: 'operating',
    stockSymbol: 'BHP',
    description: 'BHP London dual-listed office (LSE: BHP).',
  },
  {
    id: 'rio-tinto-hq',
    name: 'Rio Tinto',
    lat: 51.5074,
    lon: -0.1278,
    country: 'United Kingdom',
    city: 'London',
    siteType: 'headquarters',
    sector: 'Diversified',
    operator: 'Rio Tinto',
    mineralTypes: ['Iron Ore', 'Aluminum', 'Copper', 'Diamonds', 'Lithium'],
    status: 'operating',
    stockSymbol: 'RIO',
    description: 'Anglo-Australian mining giant. World\'s second-largest iron ore producer.',
    employees: 55000,
    marketCapUSD: 100,
  },
  {
    id: 'glencore-hq',
    name: 'Glencore',
    lat: 47.1663,
    lon: 8.5159,
    country: 'Switzerland',
    city: 'Baar',
    siteType: 'headquarters',
    sector: 'Diversified',
    operator: 'Glencore',
    mineralTypes: ['Copper', 'Cobalt', 'Zinc', 'Nickel', 'Coal', 'Oil'],
    status: 'operating',
    stockSymbol: 'GLEN.L',
    description: 'World\'s largest commodities trading and mining company. Dominant in cobalt and zinc.',
    employees: 135000,
    marketCapUSD: 60,
  },
  {
    id: 'vale-hq',
    name: 'Vale',
    lat: -22.9068,
    lon: -43.1729,
    country: 'Brazil',
    city: 'Rio de Janeiro',
    siteType: 'headquarters',
    sector: 'Iron Ore',
    operator: 'Vale',
    mineralTypes: ['Iron Ore', 'Nickel', 'Copper', 'Cobalt', 'Manganese'],
    status: 'operating',
    stockSymbol: 'VALE',
    description: 'World\'s largest iron ore and nickel producer. Critical supply chain for steel and batteries.',
    employees: 125000,
    marketCapUSD: 50,
  },
  {
    id: 'angloamerican-hq',
    name: 'Anglo American',
    lat: 51.5074,
    lon: -0.1278,
    country: 'United Kingdom',
    city: 'London',
    siteType: 'headquarters',
    sector: 'Diversified',
    operator: 'Anglo American',
    mineralTypes: ['Platinum', 'Diamonds', 'Copper', 'Iron Ore', 'Nickel', 'Coal'],
    status: 'operating',
    stockSymbol: 'AAL.L',
    description: 'Global diversified miner. Largest PGM producer through Anglo American Platinum (Amplats).',
    employees: 90000,
    marketCapUSD: 30,
  },
  {
    id: 'freeport-hq',
    name: 'Freeport-McMoRan',
    lat: 33.4484,
    lon: -112.0740,
    country: 'USA',
    city: 'Phoenix',
    siteType: 'headquarters',
    sector: 'Copper',
    operator: 'Freeport-McMoRan',
    mineralTypes: ['Copper', 'Gold', 'Molybdenum'],
    status: 'operating',
    stockSymbol: 'FCX',
    description: 'World\'s largest publicly traded copper producer. Operates Grasberg (Indonesia) and Morenci (US).',
    employees: 25000,
    marketCapUSD: 55,
  },
  {
    id: 'teck-hq',
    name: 'Teck Resources',
    lat: 49.2827,
    lon: -123.1207,
    country: 'Canada',
    city: 'Vancouver',
    siteType: 'headquarters',
    sector: 'Diversified',
    operator: 'Teck Resources',
    mineralTypes: ['Copper', 'Zinc', 'Steelmaking Coal'],
    status: 'operating',
    stockSymbol: 'TECK',
    description: 'Canada\'s largest diversified mining company. Major copper growth pipeline (QB2, Highland Valley).',
    employees: 10000,
    marketCapUSD: 18,
  },

  // ============================================================
  // GOLD / SILVER MAJORS (Headquarters)
  // ============================================================
  {
    id: 'newmont-hq',
    name: 'Newmont',
    lat: 39.7392,
    lon: -104.9903,
    country: 'USA',
    city: 'Denver',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Newmont',
    mineralTypes: ['Gold', 'Copper', 'Silver', 'Zinc', 'Lead'],
    status: 'operating',
    stockSymbol: 'NEM',
    description: 'World\'s largest gold mining company by production. Operations on 6 continents.',
    employees: 38000,
    marketCapUSD: 35,
  },
  {
    id: 'barrick-hq',
    name: 'Barrick Gold',
    lat: 43.6532,
    lon: -79.3832,
    country: 'Canada',
    city: 'Toronto',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Barrick Gold',
    mineralTypes: ['Gold', 'Copper'],
    status: 'operating',
    stockSymbol: 'GOLD',
    description: 'World\'s second-largest gold miner. Major Tier One assets in Nevada, Nevada, Mali, DRC.',
    employees: 36000,
    marketCapUSD: 30,
  },
  {
    id: 'agnico-eagle-hq',
    name: 'Agnico Eagle',
    lat: 43.6532,
    lon: -79.3832,
    country: 'Canada',
    city: 'Toronto',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Agnico Eagle',
    mineralTypes: ['Gold', 'Silver'],
    status: 'operating',
    stockSymbol: 'AEM',
    description: 'Senior gold producer with operations in Canada, Finland, Mexico, and Australia.',
    employees: 15000,
    marketCapUSD: 35,
  },
  {
    id: 'goldfields-hq',
    name: 'Gold Fields',
    lat: -26.2041,
    lon: 28.0473,
    country: 'South Africa',
    city: 'Johannesburg',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Gold Fields',
    mineralTypes: ['Gold'],
    status: 'operating',
    stockSymbol: 'GFI',
    description: 'South African gold major with assets in SA, Ghana, Australia, Peru, and Chile.',
    employees: 25000,
    marketCapUSD: 15,
  },
  {
    id: 'anglogold-hq',
    name: 'AngloGold Ashanti',
    lat: -26.2041,
    lon: 28.0473,
    country: 'South Africa',
    city: 'Johannesburg',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'AngloGold Ashanti',
    mineralTypes: ['Gold'],
    status: 'operating',
    stockSymbol: 'AU',
    description: 'Third-largest gold producer. Operations across Africa, Americas, and Australia.',
    employees: 30000,
    marketCapUSD: 12,
  },
  {
    id: 'kinross-hq',
    name: 'Kinross Gold',
    lat: 43.6532,
    lon: -79.3832,
    country: 'Canada',
    city: 'Toronto',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Kinross Gold',
    mineralTypes: ['Gold', 'Silver'],
    status: 'operating',
    stockSymbol: 'KGC',
    description: 'Senior gold producer with mines in USA, Brazil, Chile, West Africa, and Mauritania.',
    employees: 9000,
    marketCapUSD: 9,
  },
  {
    id: 'fresnillo-hq',
    name: 'Fresnillo plc',
    lat: 19.4326,
    lon: -99.1332,
    country: 'Mexico',
    city: 'Mexico City',
    siteType: 'headquarters',
    sector: 'Silver',
    operator: 'Fresnillo',
    mineralTypes: ['Silver', 'Gold', 'Lead', 'Zinc'],
    status: 'operating',
    stockSymbol: 'FRES.L',
    description: 'World\'s largest primary silver producer. Operating in Mexico since 1554.',
    employees: 12000,
    marketCapUSD: 6,
  },
  {
    id: 'pan-american-silver-hq',
    name: 'Pan American Silver',
    lat: 49.2827,
    lon: -123.1207,
    country: 'Canada',
    city: 'Vancouver',
    siteType: 'headquarters',
    sector: 'Silver',
    operator: 'Pan American Silver',
    mineralTypes: ['Silver', 'Gold', 'Zinc', 'Lead', 'Copper'],
    status: 'operating',
    stockSymbol: 'PAAS',
    description: 'Leading primary silver mining company with operations across Latin America.',
    employees: 14000,
    marketCapUSD: 5,
  },

  // ============================================================
  // BATTERY METALS / CRITICAL MINERALS (Headquarters)
  // ============================================================
  {
    id: 'albemarle-hq',
    name: 'Albemarle',
    lat: 35.2271,
    lon: -80.8431,
    country: 'USA',
    city: 'Charlotte',
    siteType: 'headquarters',
    sector: 'Lithium',
    operator: 'Albemarle',
    mineralTypes: ['Lithium', 'Bromine', 'Refining Catalysts'],
    status: 'operating',
    stockSymbol: 'ALB',
    description: 'World\'s largest lithium producer. Operates Greenbushes (Australia) and Chilean brine assets.',
    employees: 6600,
    marketCapUSD: 8,
  },
  {
    id: 'sqm-hq',
    name: 'SQM (Sociedad Química)',
    lat: -33.4569,
    lon: -70.6483,
    country: 'Chile',
    city: 'Santiago',
    siteType: 'headquarters',
    sector: 'Lithium',
    operator: 'SQM',
    mineralTypes: ['Lithium', 'Potassium', 'Iodine', 'Nitrates'],
    status: 'operating',
    stockSymbol: 'SQM',
    description: 'World\'s second-largest lithium producer. Primary operator at Salar de Atacama.',
    employees: 5400,
    marketCapUSD: 12,
  },
  {
    id: 'pilbara-minerals-hq',
    name: 'Pilbara Minerals',
    lat: -31.9505,
    lon: 115.8605,
    country: 'Australia',
    city: 'Perth',
    siteType: 'headquarters',
    sector: 'Lithium',
    operator: 'Pilbara Minerals',
    mineralTypes: ['Lithium (Spodumene)'],
    status: 'operating',
    stockSymbol: 'PLS.AX',
    description: 'Pure-play lithium miner operating Pilgangoora in Western Australia.',
    employees: 900,
    marketCapUSD: 3,
  },
  {
    id: 'mp-materials-hq',
    name: 'MP Materials',
    lat: 34.0522,
    lon: -118.2437,
    country: 'USA',
    city: 'Los Angeles',
    siteType: 'headquarters',
    sector: 'Rare Earths',
    operator: 'MP Materials',
    mineralTypes: ['Neodymium', 'Praseodymium', 'Lanthanum', 'Cerium'],
    status: 'operating',
    stockSymbol: 'MP',
    description: 'Operator of Mountain Pass, the only US rare earth mining and processing facility.',
    employees: 550,
    marketCapUSD: 2,
  },
  {
    id: 'lynas-hq',
    name: 'Lynas Rare Earths',
    lat: -31.9505,
    lon: 115.8605,
    country: 'Australia',
    city: 'Perth',
    siteType: 'headquarters',
    sector: 'Rare Earths',
    operator: 'Lynas',
    mineralTypes: ['Neodymium', 'Praseodymium', 'Heavy Rare Earths'],
    status: 'operating',
    stockSymbol: 'LYC.AX',
    description: 'Largest rare earth producer outside China. Operates Mt Weld mine and Kalgoorlie processing.',
    employees: 1400,
    marketCapUSD: 3,
  },
  {
    id: 'cmoc-hq',
    name: 'CMOC Group',
    lat: 31.2304,
    lon: 121.4737,
    country: 'China',
    city: 'Shanghai',
    siteType: 'headquarters',
    sector: 'Cobalt',
    operator: 'CMOC',
    mineralTypes: ['Cobalt', 'Copper', 'Molybdenum', 'Tungsten', 'Niobium'],
    status: 'operating',
    stockSymbol: '603993.SS',
    description: 'World\'s largest cobalt producer. Major DRC copper/cobalt operations (Tenke Fungurume).',
    employees: 25000,
    marketCapUSD: 20,
  },
  {
    id: 'cameco-hq',
    name: 'Cameco',
    lat: 52.1332,
    lon: -106.6700,
    country: 'Canada',
    city: 'Saskatoon',
    siteType: 'headquarters',
    sector: 'Uranium',
    operator: 'Cameco',
    mineralTypes: ['Uranium'],
    status: 'operating',
    stockSymbol: 'CCJ',
    description: 'World\'s largest publicly traded uranium producer. Operates Cigar Lake and McArthur River.',
    employees: 3700,
    marketCapUSD: 18,
  },
  {
    id: 'kazatomprom-hq',
    name: 'Kazatomprom',
    lat: 51.1694,
    lon: 71.4491,
    country: 'Kazakhstan',
    city: 'Astana',
    siteType: 'headquarters',
    sector: 'Uranium',
    operator: 'Kazatomprom',
    mineralTypes: ['Uranium'],
    status: 'operating',
    stockSymbol: 'KAP',
    description: 'World\'s largest uranium producer (~23% of global supply). State-owned Kazakh company.',
    employees: 22000,
    marketCapUSD: 8,
  },

  // ============================================================
  // NICKEL / PGM MAJORS (Headquarters)
  // ============================================================
  {
    id: 'nornickel-hq',
    name: 'Nornickel (Norilsk Nickel)',
    lat: 55.7558,
    lon: 37.6173,
    country: 'Russia',
    city: 'Moscow',
    siteType: 'headquarters',
    sector: 'Nickel',
    operator: 'Nornickel',
    mineralTypes: ['Nickel', 'Palladium', 'Platinum', 'Copper', 'Cobalt'],
    status: 'operating',
    stockSymbol: 'GMKN.ME',
    description: 'World\'s largest producer of palladium and high-grade nickel. Major platinum producer.',
    employees: 80000,
    marketCapUSD: 25,
  },
  {
    id: 'southern-copper-hq',
    name: 'Southern Copper',
    lat: 33.4484,
    lon: -112.0740,
    country: 'USA',
    city: 'Phoenix',
    siteType: 'headquarters',
    sector: 'Copper',
    operator: 'Grupo México / Southern Copper',
    mineralTypes: ['Copper', 'Molybdenum', 'Zinc', 'Silver', 'Gold'],
    status: 'operating',
    stockSymbol: 'SCCO',
    description: 'Largest copper reserves globally. Major operations in Mexico and Peru.',
    employees: 14000,
    marketCapUSD: 60,
  },
  {
    id: 'royalgold-hq',
    name: 'Royal Gold',
    lat: 39.7392,
    lon: -104.9903,
    country: 'USA',
    city: 'Denver',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Royal Gold',
    mineralTypes: ['Gold', 'Silver', 'Copper'],
    status: 'operating',
    stockSymbol: 'RGLD',
    description: 'Precious metals royalty and streaming company. Portfolio of 190+ royalties globally.',
    employees: 30,
    marketCapUSD: 10,
  },
  {
    id: 'wheaton-precious-hq',
    name: 'Wheaton Precious Metals',
    lat: 49.2827,
    lon: -123.1207,
    country: 'Canada',
    city: 'Vancouver',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Wheaton Precious Metals',
    mineralTypes: ['Gold', 'Silver', 'Palladium', 'Cobalt'],
    status: 'operating',
    stockSymbol: 'WPM',
    description: 'World\'s largest precious metals streaming company. Agreements on 40+ mines.',
    employees: 50,
    marketCapUSD: 22,
  },
  {
    id: 'newcrest-hq',
    name: 'Newcrest Mining',
    lat: -37.8136,
    lon: 144.9631,
    country: 'Australia',
    city: 'Melbourne',
    siteType: 'headquarters',
    sector: 'Gold',
    operator: 'Newmont/Newcrest',
    mineralTypes: ['Gold', 'Copper'],
    status: 'operating',
    stockSymbol: 'NCM.AX',
    description: 'Australia\'s largest gold miner (acquired by Newmont 2023). Cadia, Lihir, Brucejack.',
    employees: 16000,
    marketCapUSD: 20,
  },
];
