// Commodity variant: Geographic data for mine sites, processing plants, and export ports
// ~70+ mine sites spanning all major mineral types and producing regions

export type MineralType =
  | 'Gold'
  | 'Silver'
  | 'Copper'
  | 'Lithium'
  | 'Cobalt'
  | 'Rare Earths'
  | 'Nickel'
  | 'Platinum'
  | 'Palladium'
  | 'Iron Ore'
  | 'Uranium'
  | 'Aluminum'
  | 'Zinc'
  | 'Lead'
  | 'Tin'
  | 'Manganese'
  | 'Chromium'
  | 'Coal'
  | 'Molybdenum';

export type MineSiteStatus = 'producing' | 'development' | 'care-and-maintenance' | 'exploration' | 'closed';

export interface MineSite {
  id: string;
  name: string;
  lat: number;
  lon: number;
  mineral: MineralType;
  country: string;
  operator: string;
  status: MineSiteStatus;
  significance: string;
  productionRank?: string;     // e.g. "World's largest", "#2 globally"
  productionCapacity?: string; // e.g. "1.2Mt Cu/yr"
  annualOutput?: string;       // human-readable output for tooltip
  openPitOrUnderground?: 'open-pit' | 'underground' | 'in-situ' | 'both';
}

export interface ProcessingPlant {
  id: string;
  name: string;
  lat: number;
  lon: number;
  type: 'smelter' | 'refinery' | 'processing' | 'separation';
  mineral: MineralType;
  country: string;
  operator: string;
  materials?: string[];        // alternative minerals processed
  status: 'operating' | 'planned' | 'idle';
  significance: string;
  outputCapacity?: string;
  capacityTpa?: number;        // annual capacity in tonnes
}

export interface CommodityPort {
  id: string;
  name: string;
  lat: number;
  lon: number;
  country: string;
  city: string;
  commodities: MineralType[];
  annualThroughput?: string;
  annualVolumeMt?: number;     // annual volume in megatonnes
  significance: string;
}

// ============================================================
// MINE SITES — ~70 of the world's most significant operations
// ============================================================
export const MINING_SITES: MineSite[] = [

  // === GOLD ===
  {
    id: 'carlin-trend',
    name: 'Carlin Trend',
    lat: 40.73,
    lon: -116.12,
    mineral: 'Gold',
    country: 'USA',
    operator: 'Nevada Gold Mines (Barrick/Newmont JV)',
    status: 'producing',
    significance: 'Largest gold mining district in Western Hemisphere. ~3.5Moz/yr combined output.',
    productionRank: 'Western Hemisphere #1',
    openPitOrUnderground: 'both',
  },
  {
    id: 'super-pit',
    name: 'Super Pit (KCGM)',
    lat: -30.784,
    lon: 121.498,
    mineral: 'Gold',
    country: 'Australia',
    operator: 'Northern Star Resources',
    status: 'producing',
    significance: 'One of Australia\'s largest open-pit gold mines. ~600koz/yr.',
    productionRank: 'Australia #2',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'boddington',
    name: 'Boddington',
    lat: -32.795,
    lon: 116.48,
    mineral: 'Gold',
    country: 'Australia',
    operator: 'Newmont',
    status: 'producing',
    significance: 'Australia\'s largest gold mine. Also significant copper by-product.',
    productionRank: 'Australia #1',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'mponeng',
    name: 'Mponeng',
    lat: -26.486,
    lon: 27.445,
    mineral: 'Gold',
    country: 'South Africa',
    operator: 'AngloGold Ashanti',
    status: 'producing',
    significance: 'World\'s deepest gold mine (4km). High-grade underground operation.',
    productionRank: 'World deepest mine',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'olimpiada',
    name: 'Olimpiada',
    lat: 59.03,
    lon: 93.37,
    mineral: 'Gold',
    country: 'Russia',
    operator: 'Polyus',
    status: 'producing',
    significance: 'Russia\'s largest gold mine, among world\'s top 5. Siberian deposit.',
    productionRank: 'World top 5',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'lihir',
    name: 'Lihir',
    lat: -3.12,
    lon: 152.65,
    mineral: 'Gold',
    country: 'Papua New Guinea',
    operator: 'Newcrest/Newmont',
    status: 'producing',
    significance: 'Active volcanic island gold mine. ~950koz/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'obuasi',
    name: 'Obuasi',
    lat: 6.20,
    lon: -1.67,
    mineral: 'Gold',
    country: 'Ghana',
    operator: 'AngloGold Ashanti',
    status: 'producing',
    significance: 'High-grade West African gold mine. Historically one of Africa\'s largest producers.',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'pueblo-viejo',
    name: 'Pueblo Viejo',
    lat: 19.33,
    lon: -70.06,
    mineral: 'Gold',
    country: 'Dominican Republic',
    operator: 'Barrick Gold / Newmont JV',
    status: 'producing',
    significance: 'Largest gold mine in the Caribbean. ~800koz/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'detour-lake',
    name: 'Detour Lake',
    lat: 50.05,
    lon: -79.70,
    mineral: 'Gold',
    country: 'Canada',
    operator: 'Agnico Eagle',
    status: 'producing',
    significance: 'Canada\'s largest open-pit gold mine by land area. ~700koz/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'cortez',
    name: 'Cortez (Pipeline)',
    lat: 40.26,
    lon: -116.35,
    mineral: 'Gold',
    country: 'USA',
    operator: 'Nevada Gold Mines (Barrick)',
    status: 'producing',
    significance: 'Major Tier One gold mine in Nevada. Part of Nevada Gold Mines complex.',
    openPitOrUnderground: 'both',
  },
  {
    id: 'donlin-gold',
    name: 'Donlin Gold',
    lat: 61.98,
    lon: -158.08,
    mineral: 'Gold',
    country: 'USA',
    operator: 'Barrick / NovaGold JV',
    status: 'development',
    significance: 'One of the world\'s largest undeveloped gold deposits. Remote Alaska site.',
    openPitOrUnderground: 'open-pit',
  },

  // === SILVER ===
  {
    id: 'fresnillo-mine',
    name: 'Fresnillo Mine',
    lat: 23.17,
    lon: -102.87,
    mineral: 'Silver',
    country: 'Mexico',
    operator: 'Fresnillo plc',
    status: 'producing',
    significance: 'World\'s largest primary silver mine. >50Moz/yr silver output.',
    productionRank: 'World #1 silver mine',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'penasquito',
    name: 'Peñasquito',
    lat: 25.18,
    lon: -101.81,
    mineral: 'Silver',
    country: 'Mexico',
    operator: 'Newmont',
    status: 'producing',
    significance: 'Mexico\'s largest open-pit mine. World\'s largest silver producer by output. Gold/zinc/lead by-products.',
    productionRank: 'World #2 silver mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'kghm-silver',
    name: 'KGHM Copper/Silver Complex',
    lat: 51.62,
    lon: 16.24,
    mineral: 'Silver',
    country: 'Poland',
    operator: 'KGHM Polska Miedź',
    status: 'producing',
    significance: 'Europe\'s largest copper and silver producer. World\'s second-largest silver producer.',
    openPitOrUnderground: 'underground',
  },

  // === COPPER ===
  {
    id: 'escondida',
    name: 'Escondida',
    lat: -24.27,
    lon: -69.07,
    mineral: 'Copper',
    country: 'Chile',
    operator: 'BHP / Rio Tinto / JECO',
    status: 'producing',
    significance: 'World\'s largest copper mine. ~1.2Mt Cu/yr. Atacama Desert, Chile.',
    productionRank: 'World #1 copper mine',
    openPitOrUnderground: 'open-pit',
    productionCapacity: '1.2Mt Cu/yr',
  },
  {
    id: 'chuquicamata',
    name: 'Chuquicamata',
    lat: -22.30,
    lon: -68.93,
    mineral: 'Copper',
    country: 'Chile',
    operator: 'Codelco',
    status: 'producing',
    significance: 'World\'s largest open-pit copper mine by volume. Transitioning to underground.',
    productionRank: 'World largest open pit by volume',
    openPitOrUnderground: 'both',
  },
  {
    id: 'el-teniente',
    name: 'El Teniente',
    lat: -34.08,
    lon: -70.36,
    mineral: 'Copper',
    country: 'Chile',
    operator: 'Codelco',
    status: 'producing',
    significance: 'World\'s largest underground copper mine. ~430kt Cu/yr.',
    productionRank: 'World #1 underground copper mine',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'grasberg',
    name: 'Grasberg',
    lat: -4.05,
    lon: 137.12,
    mineral: 'Copper',
    country: 'Indonesia',
    operator: 'Freeport-McMoRan / Inalum',
    status: 'producing',
    significance: 'World\'s second-largest copper mine. Also world\'s largest gold mine by contained gold.',
    productionRank: 'World #2 copper, #1 gold',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'cerro-verde',
    name: 'Cerro Verde',
    lat: -16.52,
    lon: -71.60,
    mineral: 'Copper',
    country: 'Peru',
    operator: 'Freeport-McMoRan / Buenaventura / SMM',
    status: 'producing',
    significance: 'Major Peruvian copper producer. ~500kt Cu/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'antamina',
    name: 'Antamina',
    lat: -9.53,
    lon: -77.04,
    mineral: 'Copper',
    country: 'Peru',
    operator: 'BHP / Glencore / Teck / Mitsubishi',
    status: 'producing',
    significance: 'World-class copper-zinc mine in the Andes. ~460kt Cu/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'morenci',
    name: 'Morenci',
    lat: 33.08,
    lon: -109.36,
    mineral: 'Copper',
    country: 'USA',
    operator: 'Freeport-McMoRan',
    status: 'producing',
    significance: 'Largest copper mine in North America. ~500kt Cu/yr.',
    productionRank: 'North America #1 copper mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'kamoa-kakula',
    name: 'Kamoa-Kakula',
    lat: -5.54,
    lon: 25.96,
    mineral: 'Copper',
    country: 'DRC',
    operator: 'Ivanhoe Mines / Zijin Mining',
    status: 'producing',
    significance: 'Highest-grade major copper mine discovered in 30 years. Fastest-growing producer.',
    productionRank: 'World #3 copper mine (growing)',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'oyu-tolgoi',
    name: 'Oyu Tolgoi',
    lat: 43.00,
    lon: 107.00,
    mineral: 'Copper',
    country: 'Mongolia',
    operator: 'Rio Tinto / Turquoise Hill',
    status: 'producing',
    significance: 'World\'s third-largest copper-gold deposit. Underground expansion ramping up.',
    openPitOrUnderground: 'both',
  },
  {
    id: 'lumwana',
    name: 'Lumwana',
    lat: -12.52,
    lon: 25.36,
    mineral: 'Copper',
    country: 'Zambia',
    operator: 'Barrick Gold',
    status: 'producing',
    significance: 'One of Africa\'s largest copper mines. ~140kt Cu/yr. Major Zambian producer.',
    openPitOrUnderground: 'open-pit',
  },

  // === LITHIUM ===
  {
    id: 'greenbushes',
    name: 'Greenbushes',
    lat: -33.86,
    lon: 116.01,
    mineral: 'Lithium',
    country: 'Australia',
    operator: 'Talison Lithium (Albemarle / Tianqi)',
    status: 'producing',
    significance: 'World\'s largest hard-rock lithium mine. Highest-grade spodumene deposit.',
    productionRank: 'World #1 hard-rock lithium',
    openPitOrUnderground: 'open-pit',
    productionCapacity: '~1.5Mt spodumene/yr',
  },
  {
    id: 'salar-atacama',
    name: 'Salar de Atacama',
    lat: -23.50,
    lon: -68.33,
    mineral: 'Lithium',
    country: 'Chile',
    operator: 'SQM / Albemarle',
    status: 'producing',
    significance: 'World\'s largest and lowest-cost lithium brine source. ~150kt LCE/yr.',
    productionRank: 'World #1 lithium brine',
    openPitOrUnderground: 'in-situ',
    productionCapacity: '150kt LCE/yr',
  },
  {
    id: 'pilgangoora',
    name: 'Pilgangoora',
    lat: -21.03,
    lon: 118.91,
    mineral: 'Lithium',
    country: 'Australia',
    operator: 'Pilbara Minerals',
    status: 'producing',
    significance: 'Major hard-rock lithium mine. World\'s largest spodumene project after Greenbushes.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'olaroz',
    name: 'Olaroz',
    lat: -23.47,
    lon: -66.81,
    mineral: 'Lithium',
    country: 'Argentina',
    operator: 'Allkem / Toyota Tsusho',
    status: 'producing',
    significance: 'Key Argentina lithium brine operation. Part of the Lithium Triangle.',
    openPitOrUnderground: 'in-situ',
  },
  {
    id: 'cauchari-olaroz',
    name: 'Cauchari-Olaroz',
    lat: -23.82,
    lon: -66.89,
    mineral: 'Lithium',
    country: 'Argentina',
    operator: 'Lithium Americas / Ganfeng',
    status: 'producing',
    significance: 'One of Argentina\'s largest lithium brine projects. Recently commenced production.',
    openPitOrUnderground: 'in-situ',
  },
  {
    id: 'silver-peak',
    name: 'Silver Peak',
    lat: 37.75,
    lon: -117.65,
    mineral: 'Lithium',
    country: 'USA',
    operator: 'Albemarle',
    status: 'producing',
    significance: 'Only active US lithium mine. Nevada brine operation since 1966.',
    openPitOrUnderground: 'in-situ',
  },
  {
    id: 'thacker-pass',
    name: 'Thacker Pass',
    lat: 41.85,
    lon: -118.15,
    mineral: 'Lithium',
    country: 'USA',
    operator: 'Lithium Americas',
    status: 'development',
    significance: 'Largest known lithium deposit in the US. Under development in Nevada.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'manono',
    name: 'Manono',
    lat: -7.30,
    lon: 27.41,
    mineral: 'Lithium',
    country: 'DRC',
    operator: 'AVZ Minerals',
    status: 'development',
    significance: 'World\'s largest hard-rock lithium deposit. DRC asset under development.',
    openPitOrUnderground: 'open-pit',
  },

  // === COBALT ===
  {
    id: 'mutanda',
    name: 'Mutanda',
    lat: -10.78,
    lon: 25.80,
    mineral: 'Cobalt',
    country: 'DRC',
    operator: 'Glencore',
    status: 'producing',
    significance: 'World\'s largest cobalt mine. ~25kt Co/yr when at full capacity.',
    productionRank: 'World #1 cobalt mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'tenke-fungurume',
    name: 'Tenke Fungurume',
    lat: -10.61,
    lon: 26.16,
    mineral: 'Cobalt',
    country: 'DRC',
    operator: 'CMOC',
    status: 'producing',
    significance: 'Major cobalt-copper producer. Chinese-owned. ~17kt Co/yr.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'kamoto',
    name: 'Kamoto (KOV)',
    lat: -10.87,
    lon: 25.55,
    mineral: 'Cobalt',
    country: 'DRC',
    operator: 'Glencore / Katanga Mining',
    status: 'producing',
    significance: 'Major DRC cobalt-copper underground mine.',
    openPitOrUnderground: 'underground',
  },

  // === RARE EARTHS ===
  {
    id: 'bayan-obo',
    name: 'Bayan Obo',
    lat: 41.76,
    lon: 109.95,
    mineral: 'Rare Earths',
    country: 'China',
    operator: 'China Northern Rare Earth Group',
    status: 'producing',
    significance: 'World\'s largest rare earth mine. ~45% of global REE production from this single site.',
    productionRank: 'World #1 REE mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'mountain-pass',
    name: 'Mountain Pass',
    lat: 35.47,
    lon: -115.53,
    mineral: 'Rare Earths',
    country: 'USA',
    operator: 'MP Materials',
    status: 'producing',
    significance: 'Only significant rare earth mine and processor in the US. Strategic national asset.',
    productionRank: 'US #1 REE mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'mount-weld',
    name: 'Mount Weld',
    lat: -28.86,
    lon: 122.17,
    mineral: 'Rare Earths',
    country: 'Australia',
    operator: 'Lynas Rare Earths',
    status: 'producing',
    significance: 'Highest-grade rare earth deposit outside China. Key non-Chinese REE source.',
    productionRank: 'World #2 REE mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'southern-ion-adsorption',
    name: 'Southern China REE',
    lat: 25.85,
    lon: 114.93,
    mineral: 'Rare Earths',
    country: 'China',
    operator: 'Multiple Chinese operators',
    status: 'producing',
    significance: 'Jiangxi/Guangdong ion-adsorption clay deposits. Key source of heavy rare earths (dysprosium, terbium) critical for EV motors.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'kvanefjeld',
    name: 'Kvanefjeld',
    lat: 60.96,
    lon: -47.00,
    mineral: 'Rare Earths',
    country: 'Greenland',
    operator: 'Energy Transition Minerals',
    status: 'exploration',
    significance: 'World-class REE + uranium deposit in Greenland. Subject to Greenland political debate.',
  },

  // === NICKEL ===
  {
    id: 'weda-bay',
    name: 'Weda Bay / Halmahera',
    lat: 0.47,
    lon: 127.94,
    mineral: 'Nickel',
    country: 'Indonesia',
    operator: 'Tsingshan / Eramet',
    status: 'producing',
    significance: 'Largest nickel pig iron (NPI) production hub. Core of Indonesia\'s nickel dominance.',
    productionRank: 'Indonesia nickel #1 region',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'morowali',
    name: 'Morowali Industrial Park',
    lat: -2.10,
    lon: 121.90,
    mineral: 'Nickel',
    country: 'Indonesia',
    operator: 'Tsingshan Group (various)',
    status: 'producing',
    significance: 'Largest integrated nickel production hub globally. Drives ~50% of world\'s battery-grade nickel.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'norilsk-mine',
    name: 'Norilsk Complex',
    lat: 69.33,
    lon: 88.21,
    mineral: 'Nickel',
    country: 'Russia',
    operator: 'Nornickel',
    status: 'producing',
    significance: 'World\'s largest palladium mine and top nickel producer. Arctic Siberian site.',
    productionRank: 'World #1 palladium, #2 nickel',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'voiseys-bay',
    name: 'Voisey\'s Bay',
    lat: 56.37,
    lon: -62.08,
    mineral: 'Nickel',
    country: 'Canada',
    operator: 'Vale',
    status: 'producing',
    significance: 'High-grade nickel-cobalt-copper mine in Labrador. Strategic Canadian deposit.',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'goro',
    name: 'Goro (Vale Nouvelle-Calédonie)',
    lat: -22.27,
    lon: 167.00,
    mineral: 'Nickel',
    country: 'New Caledonia',
    operator: 'Prony Resources',
    status: 'producing',
    significance: 'Major laterite nickel operation. Battery-grade nickel and cobalt production.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'taganito',
    name: 'Taganito',
    lat: 9.15,
    lon: 125.77,
    mineral: 'Nickel',
    country: 'Philippines',
    operator: 'Sumitomo / DMCI',
    status: 'producing',
    significance: 'Key Philippine nickel laterite mine. Major Japanese nickel supply source.',
    openPitOrUnderground: 'open-pit',
  },

  // === PLATINUM / PALLADIUM ===
  {
    id: 'mogalakwena',
    name: 'Mogalakwena',
    lat: -24.05,
    lon: 28.76,
    mineral: 'Platinum',
    country: 'South Africa',
    operator: 'Anglo American Platinum',
    status: 'producing',
    significance: 'World\'s largest open-pit platinum mine. Bushveld Igneous Complex.',
    productionRank: 'World #1 open-pit PGM mine',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'marikana',
    name: 'Marikana / Rustenburg',
    lat: -25.68,
    lon: 27.38,
    mineral: 'Platinum',
    country: 'South Africa',
    operator: 'Sibanye-Stillwater',
    status: 'producing',
    significance: 'Major Bushveld Complex platinum operations. Historically significant labor site.',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'zimplats',
    name: 'Zimplats',
    lat: -18.12,
    lon: 30.45,
    mineral: 'Platinum',
    country: 'Zimbabwe',
    operator: 'Impala Platinum',
    status: 'producing',
    significance: 'Zimbabwe\'s largest mining company. World\'s third-largest PGM producer.',
    openPitOrUnderground: 'both',
  },
  {
    id: 'stillwater',
    name: 'Stillwater',
    lat: 45.37,
    lon: -109.93,
    mineral: 'Palladium',
    country: 'USA',
    operator: 'Sibanye-Stillwater',
    status: 'producing',
    significance: 'Only significant PGM mine in North America. Primary US palladium source.',
    productionRank: 'North America #1 PGM',
    openPitOrUnderground: 'underground',
  },

  // === IRON ORE ===
  {
    id: 'pilbara',
    name: 'Pilbara Iron Ore (BHP)',
    lat: -22.50,
    lon: 119.00,
    mineral: 'Iron Ore',
    country: 'Australia',
    operator: 'BHP',
    status: 'producing',
    significance: 'BHP\'s Pilbara hub — world\'s most productive iron ore mining region. ~280Mt/yr.',
    productionRank: 'BHP Pilbara iron ore hub',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'pilbara-rio',
    name: 'Pilbara Iron Ore (Rio Tinto)',
    lat: -22.70,
    lon: 118.60,
    mineral: 'Iron Ore',
    country: 'Australia',
    operator: 'Rio Tinto',
    status: 'producing',
    significance: 'Rio Tinto\'s Pilbara operations — 16 mines feeding 4 port facilities. ~330Mt/yr.',
    productionRank: 'World #1 iron ore producer (Rio)',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'carajas',
    name: 'Carajás',
    lat: -5.83,
    lon: -50.61,
    mineral: 'Iron Ore',
    country: 'Brazil',
    operator: 'Vale',
    status: 'producing',
    significance: 'World\'s largest iron ore mine by proven reserves. Highest grade iron ore (~67% Fe).',
    productionRank: 'World #1 iron ore reserve',
    openPitOrUnderground: 'open-pit',
    productionCapacity: '~180Mt/yr',
  },
  {
    id: 'sishen',
    name: 'Sishen',
    lat: -27.79,
    lon: 22.98,
    mineral: 'Iron Ore',
    country: 'South Africa',
    operator: 'Kumba Iron Ore (Anglo American)',
    status: 'producing',
    significance: 'Africa\'s largest iron ore mine. Major export source for European and Asian steel mills.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'kiruna',
    name: 'Kiruna',
    lat: 67.85,
    lon: 20.32,
    mineral: 'Iron Ore',
    country: 'Sweden',
    operator: 'LKAB',
    status: 'producing',
    significance: 'Europe\'s largest iron ore mine. Undergoing city relocation due to mine expansion.',
    openPitOrUnderground: 'underground',
  },

  // === URANIUM ===
  {
    id: 'mcarthur-river',
    name: 'McArthur River',
    lat: 57.76,
    lon: -105.03,
    mineral: 'Uranium',
    country: 'Canada',
    operator: 'Cameco',
    status: 'producing',
    significance: 'World\'s highest-grade uranium mine. 25x average uranium ore grade. Saskatchewan, Canada.',
    productionRank: 'World #1 by grade',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'cigar-lake',
    name: 'Cigar Lake',
    lat: 57.67,
    lon: -105.61,
    mineral: 'Uranium',
    country: 'Canada',
    operator: 'Cameco / Orano',
    status: 'producing',
    significance: 'World\'s largest high-grade uranium deposit currently in production.',
    productionRank: 'World #1 by production volume (high-grade)',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'kazakh-isu',
    name: 'Kazakhstan ISL Fields',
    lat: 43.60,
    lon: 65.40,
    mineral: 'Uranium',
    country: 'Kazakhstan',
    operator: 'Kazatomprom',
    status: 'producing',
    significance: 'Cluster of in-situ leaching uranium operations. Kazakhstan produces ~40% of world supply.',
    productionRank: 'World #1 uranium producer country',
    openPitOrUnderground: 'in-situ',
  },
  {
    id: 'olympic-dam',
    name: 'Olympic Dam',
    lat: -30.44,
    lon: 136.89,
    mineral: 'Uranium',
    country: 'Australia',
    operator: 'BHP',
    status: 'producing',
    significance: 'World\'s largest known uranium ore body. Also produces copper, gold, silver.',
    productionRank: 'World #1 uranium ore body',
    openPitOrUnderground: 'underground',
  },
  {
    id: 'rossing',
    name: 'Rössing',
    lat: -22.45,
    lon: 14.99,
    mineral: 'Uranium',
    country: 'Namibia',
    operator: 'China National Uranium Corp',
    status: 'producing',
    significance: 'One of the world\'s largest open-pit uranium mines. Chinese-owned since 2019.',
    openPitOrUnderground: 'open-pit',
  },
  {
    id: 'husab',
    name: 'Husab',
    lat: -22.46,
    lon: 15.18,
    mineral: 'Uranium',
    country: 'Namibia',
    operator: 'China General Nuclear Power',
    status: 'producing',
    significance: 'Second-largest uranium mine globally by production. 100% Chinese-owned.',
    productionRank: 'World #2 uranium mine',
    openPitOrUnderground: 'open-pit',
  },
];

// ============================================================
// PROCESSING PLANTS — Smelters, refineries, separation facilities
// ============================================================
export const PROCESSING_PLANTS: ProcessingPlant[] = [
  // Rare Earth Processing
  {
    id: 'baotou-ree',
    name: 'Baotou REE Processing Complex',
    lat: 40.66,
    lon: 109.84,
    type: 'separation',
    mineral: 'Rare Earths',
    country: 'China',
    operator: 'China Northern Rare Earth Group',
    status: 'operating',
    significance: 'World\'s largest rare earth processing hub. Processes ore from Bayan Obo.',
    outputCapacity: '~70% of global REE separation',
  },
  {
    id: 'lynas-lamp',
    name: 'Lynas Advanced Materials Plant (LAMP)',
    lat: 4.26,
    lon: 103.35,
    type: 'separation',
    mineral: 'Rare Earths',
    country: 'Malaysia',
    operator: 'Lynas Rare Earths',
    status: 'operating',
    significance: 'Largest rare earth processing facility outside China. Processes Mt Weld ore.',
    outputCapacity: '~10kt NdPr oxide/yr',
  },
  {
    id: 'mp-processing',
    name: 'Mountain Pass Processing',
    lat: 35.47,
    lon: -115.53,
    type: 'processing',
    mineral: 'Rare Earths',
    country: 'USA',
    operator: 'MP Materials',
    status: 'operating',
    significance: 'US rare earth concentrate processing. Building downstream magnet manufacturing.',
  },
  // Lithium Processing
  {
    id: 'ganzhou-lithium',
    name: 'Ganzhou Lithium Hub',
    lat: 25.85,
    lon: 114.93,
    type: 'refinery',
    mineral: 'Lithium',
    country: 'China',
    operator: 'Ganfeng / multiple Chinese processors',
    status: 'operating',
    significance: 'China\'s major lithium chemical refining hub. Processes spodumene into battery-grade lithium.',
    outputCapacity: '~200kt LCE/yr',
  },
  {
    id: 'kwinana-lithium',
    name: 'Kwinana Lithium Refinery',
    lat: -32.24,
    lon: 115.77,
    type: 'refinery',
    mineral: 'Lithium',
    country: 'Australia',
    operator: 'Tianqi Lithium',
    status: 'operating',
    significance: 'First lithium hydroxide refinery in Australia. Processes Greenbushes concentrate.',
    outputCapacity: '24kt LiOH/yr',
  },
  // Copper Smelters
  {
    id: 'chagres-smelter',
    name: 'Chagres Copper Smelter',
    lat: -32.49,
    lon: -70.78,
    type: 'smelter',
    mineral: 'Copper',
    country: 'Chile',
    operator: 'Anglo American',
    status: 'operating',
    significance: 'Major Chilean copper smelter. Part of integrated Andean copper production chain.',
  },
  {
    id: 'nkana-smelter',
    name: 'Nkana Copper Smelter',
    lat: -12.82,
    lon: 28.22,
    type: 'smelter',
    mineral: 'Copper',
    country: 'Zambia',
    operator: 'Glencore / Mopani Copper',
    status: 'operating',
    significance: 'Key Zambian copper smelter and refinery on the Copperbelt.',
  },
  {
    id: 'aurubis-hamburg',
    name: 'Aurubis Hamburg',
    lat: 53.53,
    lon: 10.03,
    type: 'refinery',
    mineral: 'Copper',
    country: 'Germany',
    operator: 'Aurubis',
    status: 'operating',
    significance: 'Europe\'s largest copper smelter. Major recycled copper processor.',
    outputCapacity: '~1Mt refined copper/yr',
  },
  // Gold Refineries
  {
    id: 'rand-refinery',
    name: 'Rand Refinery',
    lat: -26.16,
    lon: 28.16,
    type: 'refinery',
    mineral: 'Gold',
    country: 'South Africa',
    operator: 'Rand Refinery (Consortium)',
    status: 'operating',
    significance: 'World\'s largest gold refinery by cumulative output. Processes most of SA gold production.',
    outputCapacity: '~700t gold/yr',
  },
  {
    id: 'pamp-refinery',
    name: 'PAMP Refinery',
    lat: 46.11,
    lon: 8.92,
    type: 'refinery',
    mineral: 'Gold',
    country: 'Switzerland',
    operator: 'MKS PAMP',
    status: 'operating',
    significance: 'Switzerland\'s leading precious metals refinery. Produces LBMA-accredited gold bars.',
  },
  // Nickel Processing
  {
    id: 'norilsk-smelter',
    name: 'Norilsk Nickel Smelter',
    lat: 69.33,
    lon: 88.20,
    type: 'smelter',
    mineral: 'Nickel',
    country: 'Russia',
    operator: 'Nornickel',
    status: 'operating',
    significance: 'World\'s largest nickel and palladium smelter. Also major SO2 emitter (Arctic pollution concern).',
    outputCapacity: '~250kt Ni/yr, ~90t Pd/yr',
  },
];

// ============================================================
// COMMODITY PORTS — Major mineral export/import terminals
// ============================================================
export const COMMODITY_PORTS: CommodityPort[] = [
  {
    id: 'port-hedland',
    name: 'Port Hedland',
    lat: -20.31,
    lon: 118.58,
    country: 'Australia',
    city: 'Port Hedland',
    commodities: ['Iron Ore'],
    annualThroughput: '~580Mt/yr iron ore',
    significance: 'World\'s largest bulk export port. Handles ~18% of global seaborne iron ore trade.',
  },
  {
    id: 'dampier-port',
    name: 'Dampier (Rio Tinto)',
    lat: -20.66,
    lon: 116.72,
    country: 'Australia',
    city: 'Dampier',
    commodities: ['Iron Ore'],
    annualThroughput: '~200Mt/yr iron ore',
    significance: 'Rio Tinto\'s primary iron ore export terminal. Part of Pilbara port network.',
  },
  {
    id: 'punta-patache',
    name: 'Coloso Port / Antofagasta',
    lat: -23.65,
    lon: -70.41,
    country: 'Chile',
    city: 'Antofagasta',
    commodities: ['Copper'],
    annualThroughput: '~1.2Mt Cu/yr',
    significance: 'Chile\'s primary copper export port. Gateway for Escondida and northern Atacama mines.',
  },
  {
    id: 'santos-brazil',
    name: 'Port of Santos',
    lat: -23.96,
    lon: -46.33,
    country: 'Brazil',
    city: 'Santos',
    commodities: ['Iron Ore'],
    annualThroughput: '~130Mt/yr iron ore',
    significance: 'Brazil\'s largest port. Key iron ore and agricultural export terminal.',
  },
  {
    id: 'richards-bay',
    name: 'Richards Bay Coal Terminal',
    lat: -28.80,
    lon: 32.07,
    country: 'South Africa',
    city: 'Richards Bay',
    commodities: ['Coal'],
    annualThroughput: '~70Mt/yr coal',
    significance: 'Africa\'s largest dry bulk export terminal. Primary South African coal export point.',
  },
  {
    id: 'mombasa-port',
    name: 'Port of Mombasa',
    lat: -4.04,
    lon: 39.67,
    country: 'Kenya',
    city: 'Mombasa',
    commodities: ['Cobalt', 'Copper'],
    annualThroughput: '~35Mt/yr general cargo',
    significance: 'Primary export gateway for DRC and Zambia cobalt and copper.',
  },
  {
    id: 'walvis-bay',
    name: 'Walvis Bay',
    lat: -22.96,
    lon: 14.50,
    country: 'Namibia',
    city: 'Walvis Bay',
    commodities: ['Uranium'],
    annualThroughput: 'Major Namibian uranium export point',
    significance: 'Primary export port for Namibian uranium from Rössing and Husab mines.',
  },
  {
    id: 'tema-ghana',
    name: 'Tema Port',
    lat: 5.64,
    lon: -0.01,
    country: 'Ghana',
    city: 'Tema',
    commodities: ['Gold'],
    annualThroughput: '~130t gold/yr',
    significance: 'Primary gold export gateway for Ghana, one of Africa\'s largest gold producers.',
  },
  {
    id: 'callao-peru',
    name: 'Port of Callao',
    lat: -12.05,
    lon: -77.15,
    country: 'Peru',
    city: 'Callao',
    commodities: ['Copper', 'Gold', 'Zinc', 'Silver'],
    annualThroughput: '~3Mt metals/yr',
    significance: 'Peru\'s main port. Primary export point for Andean copper, zinc, and silver production.',
  },
  {
    id: 'tianjin-port',
    name: 'Port of Tianjin',
    lat: 38.99,
    lon: 117.72,
    country: 'China',
    city: 'Tianjin',
    commodities: ['Iron Ore', 'Copper', 'Aluminum'],
    annualThroughput: '~600Mt/yr total',
    significance: 'China\'s largest commodity import port. Primary iron ore, copper concentrate, and LME metals gateway.',
  },
  {
    id: 'lme-warehouse-antwerp',
    name: 'LME Antwerp Warehouse Hub',
    lat: 51.23,
    lon: 4.41,
    country: 'Belgium',
    city: 'Antwerp',
    commodities: ['Copper', 'Aluminum', 'Zinc', 'Nickel'],
    significance: 'Major LME-licensed metals warehouse network in Europe. Zinc and copper storage hub.',
  },
];
